---
ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

_minio:
  base_path: "/home/minio"
  cluster_name: jack-kr-minio
  domain: "jtest.pivotal.io"
  download: false
  bin_type: docker  # rpm, bin
  release_date: 20250422221226.0.0        # Last Release to Support Full Feature which License is not Required
  bin_release_date: 2025-04-22T22-12-26Z
  patch_version: 1
  download_url: https://dl.minio.io/server/minio/release/linux-amd64/archive
  server_url: https://dl.minio.io/server/minio/release/linux-amd64/minio
  os_version: el9
  arch_type: x86_64
  access_key: minioadmin
  secret_key: changeme
  server_checksum:
  user: minio
  group: minio
  service: "minio"
  user_home: /home/minio
  config: "/home/minio/.minio/config.json"
  bin: /usr/local/bin/minio
  bin_dir: /usr/local/bin
  listen_address: 0.0.0.0
  api_port: 9000
  console_port: 9001
  http_port: 80
  https_port: 443
  ec:
    stripe_size: 16
    parity: 4
  volumes:
    - { dev: "/dev/nvme0n1", dir: "/data01", fs: "xfs", dt_alias: "/data1" }
    - { dev: "/dev/nvme0n2", dir: "/data02", fs: "xfs", dt_alias: "/data2" }
    - { dev: "/dev/nvme0n3", dir: "/data03", fs: "xfs", dt_alias: "/data3" }
    - { dev: "/dev/nvme0n4", dir: "/data04", fs: "xfs", dt_alias: "/data4" }
  client_admin_host:
  check_calendar: weekly
  user_id:
  root_user: minioadmin
  root_password: changeme
  host_num: "{{ groups['all'] | length }}"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.17"
    ipaddr1: "192.168.1.17"
    ipaddr2: "192.168.2.17"
  client:
    net:
      type: "virtual"              # Or Physical
      cores: 1
      ipaddr0: "192.168.0.17"
      ipaddr1: "192.168.1.17"
      ipaddr2: "192.168.2.17"
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05", "rk9-node06" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]
  debug_opt: ""
  # python -c "import uuid; print str(uuid.uuid4().get_hex().upper()[0:20])"
  # python -c "import uuid; print str(uuid.uuid4().get_hex()[0:40])"


_certgen:
  download: false
  download_url: https://github.com/minio/certgen/releases/download
  major_version: 1
  minor_version: 3
  patch_version: 0
  os: linux
  arch: amd64


_ssl:
  ssl_dir: "{{ _minio.base_path }}/certs"
  ssl_days: 3660
  ssl_country: "KR"
  ssl_state: "Seoul"
  ssl_location: "Guro"
  ssl_organization: "VMware"
  ssl_organization_unit: "Tanzu"
  ssl_common_name: "jtest.pivotal.io"
  ssl_email: "jomoon@pivotal.io"


_common:
  sudo_user: jomoon
  sudo_group: jomoon
  sudo_user_home_dir: "/home/jomoon"


_vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

