---
ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


_minio:
  base_path: "/home/minio"
  cluster_name: jack-kr-minio
  domain: "jtest.pivotal.io"
  major_version: "15"
  minor_version: "5"
  patch_version: "1"
  build_version: "1"
  # release_date: 20231025
  release_date: 20250422221226.0.0-1  # Last Release to Support Full Feature which is Not Community Version
  os_version: el9
  arch_type: x86_64
  bin_type: rpm
  user: jomoon
  group: jomoon
  password: 'changeme'
  sudo_user_dir: "/home/jomoon"
  repo_url: ""
  download_url: ""
  download: false
  host_num: "{{ groups['all'] | length }}"
  enable_ssl: true
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  client:
    net:
      type: "virtual"              # Or Physical
      cores: 1
      ipaddr0: "192.168.0.19"
      ipaddr1: "192.168.1.19"
      ipaddr2: "192.168.2.19"
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05", "rk9-node06" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]
  debug_opt: ""  # --debug
  access_key: minioadmin
  secret_key: changeme


_mc:
  release_date: 20250521015954.0.0-1


_ssl:
  ssl_dir: "{{ _minio.base_path }}/certs"
  ssl_days: 3660
  ssl_country: "KR"
  ssl_state: "Seoul"
  ssl_location: "GangNam"
  ssl_organization: "Pivotal"
  ssl_common_name: "jtest.pivotal.io"
  ssl_email: "jomoon@pivotal.io"


_common:
  sudo_user: jomoon
  sudo_group: jomoon
  sudo_user_home_dir: "/home/jomoon"


_vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

