---
- name: Apply Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "net.ipv4.conf.lo.arp_ignore" ,   value: "1" }
    - { key: "net.ipv4.conf.lo.arp_announce",  value: "2" }
    - { key: "net.ipv4.conf.all.arp_ignore" ,  value: "1" }
    - { key: "net.ipv4.conf.all.arp_announce", value: "2" }
  when: inventory_hostname in groups['workers']
  notify: Reload Sysctl


- name: Apply Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "net.ipv4.ip_forward",            value: "1" } # In order for the Keepalived service to forward network packets properly to the real servers, each router node must have IP forwarding turned on in the kernel
    - { key: "net.ipv4.ip_nonlocal_bind",      value: "1" } # Load balancing in HAProxy also requires the ability to bind to an IP address that is nonlocal, meaning that it is not assigned to a device on the local system. This allows a running load balancer instance to bind to a an IP that is not local for failover.
  when: inventory_hostname in groups['lb']
  notify: Reload Sysctl


- name: Process packets destined for VIP and Port by Real Server
  shell: |
    iptables -t nat -A PREROUTING -p tcp -d  {{ item.ipaddr.split('/')[:-1] | join('/') }} \
    --dport {{ item.src_port }} -j REDIRECT
  register: process_package
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['lb']
  # iptables -t mangle -A PREROUTING -p tcp -d {{ item.ipaddr.split('/')[:-1] | join('/') }} \
  # -m multiport --dport 80,443 -j MARK --set-mark 80


- name: Process packets destined for VIP and Port by Real Server
  shell: |
    iptables -I INPUT -p vrrp -m comment --comment "VRRP" -j ACCEPT
  register: process_package
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['lb']

