---
- name: Create ARP table entries for Virtaul IP Addresses on Real Server
  shell: |
    firewall-cmd --permanent --direct --add-rule ipv4 nat PREROUTING 0 \
    -d  {{ item.ipaddr.split('/')[:-1] | join('/') }} -p tcp|udp -m tcp|udp --dport port -j REDIRECT
  register: create_arp_table_entries
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']

