---
- name: Process packets destined for VIP and Port by Real Server
  shell: |
    iptables -I INPUT -p vrrp -m comment --comment "VRRP" -j ACCEPT
  register: process_package
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['lb']


- name: Process packets destined for VIP and Port by Real Server
  shell: |
    iptables -t nat -A PREROUTING -p tcp -d {{ item.ipaddr.split('/')[:-1] | join('/') }} \
    -m multiport --dport 9000,9001 -j REDIRECT
  register: process_package
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['lb']
# iptables -t nat -A PREROUTING -p tcp -d  {{ item.ipaddr.split('/')[:-1] | join('/') }} \
#  --dport {{ item.src_port }} -j REDIRECT

