---
- name: Create ARP table entries for Virtaul IP Addresses on Real Server
  shell: |
    arptables -A IN -d  {{ item.ipaddr.split('/')[:-1] | join('/') }}  -j DROP
  register: create_arp_table_entries
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']


- name: Create ARP table entries for Virtaul IP Addresses on Real Server
  shell: |
    arptables -A OUT -s {{ item.ipaddr.split('/')[:-1] | join('/') }} -j mangle \
    --mangle-ip-s {{ hostvars[inventory_hostname][_netdev].ipv4.address }}
  register: create_arp_table_entries
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']


# This will cause the real servers to ignore all ARP requests for the virtual IP addresses
# and change any outgoing ARP responses which might otherwise contain the virtual IP
# so that they contain the real IP of the server instead.
# The only node that should respond to ARP requests for any of the VIPs is the current active LVS node.


- name: Configure Virutal IP Address for Direct Routing
  shell: |
    ip addr add {{ item.ipaddr.split('/')[:-1] | join('/') }} {{ netdev1 }}:{{ item.netidx }}
  register: config_direct_routing_vip
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']

