---
- name: Apply Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "net.ipv4.conf.lo.arp_ignore" ,   value: "1" }
    - { key: "net.ipv4.conf.lo.arp_announce",  value: "2" }
    - { key: "net.ipv4.conf.all.arp_ignore" ,  value: "1" }
    - { key: "net.ipv4.conf.all.arp_announce", value: "2" }
  when: inventory_hostname in groups['workers']
  notify: Reload Sysctl


- name: Apply Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "net.ipv4.ip_forward",            value: "1" } # In order for the Keepalived service to forward network packets properly to the real servers, each router node must have IP forwarding turned on in the kernel
    - { key: "net.ipv4.ip_nonlocal_bind",      value: "1" } # Load balancing in HAProxy also requires the ability to bind to an IP address that is nonlocal, meaning that it is not assigned to a device on the local system. This allows a running load balancer instance to bind to a an IP that is not local for failover.
  when: inventory_hostname in groups['lb']
  notify: Reload Sysctl


- name: Create ARP table entries for Virtaul IP Addresses on Real Server
  shell: |
    arptables -A IN -d  {{ item.ipaddr.split('/')[:-1] | join('/') }}  -j DROP
  register: create_arp_table_entries
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']


- name: Create ARP table entries for Virtaul IP Addresses on Real Server
  shell: |
    arptables -A OUT -s {{ item.ipaddr.split('/')[:-1] | join('/') }} -j mangle \
    --mangle-ip-s {{ hostvars[inventory_hostname][_netdev].ipv4.address }}
  register: create_arp_table_entries
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']

# This will cause the real servers to ignore all ARP requests for the virtual IP addresses
# and change any outgoing ARP responses which might otherwise contain the virtual IP
# so that they contain the real IP of the server instead.
# The only node that should respond to ARP requests for any of the VIPs is the current active LVS node.


- name: Configure Virutal IP Address for Direct Routing
  shell: |
    ip addr add {{ item.ipaddr.split('/')[:-1] | join('/') }} {{ netdev1 }}:{{ item.netidx }}
  register: config_direct_routing_vip
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']

