---
- name: Install Keepalived
  package:
    name: keepalived
    state: latest


- block:

   - name: Install Postfix to send Notifications
     package:
       name: ['postfix', 'mailutils']
       state: present
   - name: Start and enable postfix
     service:
       name: postfix
       state: started
       enabled: yes

  when: _keepalived.notifications_email | default(False)


- name: Copy Check Script
  template:
    src: "templates/{{ _keepalived.check_script_name }}.sh.j2"
    dest: "/etc/keepalived/check_script.sh"
    mode: 0755
    owner: root
    group: root


- name: Install Email Notification Script
  template:
    src: "templates/email_notify.sh.j2"
    dest: "/etc/keepalived/email_notify.sh"
    mode: 0755
    owner: root
    group: root


- name: Copy Keepalived Configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf


- name: Start Keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes

