---
- name: Remove Direct Routing with IPtables
  shell: |
    iptables -F
  tags: remove
  when: iptables is defined and iptables == true


- name: Configure Direct Routing with ARPtables
  shell: |
    arptables -F
  tags: remove
  when: arptables is defined and arptables == true


- name: Configure Direct Routing with Firewalld
  shell: |
    firewall-cmd --complete-reload
    firewall-cmd --permanent --reset
    firewall-cmd --reload
    systemctl stop firewalld
  tags: remove
  when: firewalld is defined and firewalld == true


- name: Remove Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: absent
  with_items:
    - { key: "net.ipv4.conf.lo.arp_ignore" ,   value: "0" }
    - { key: "net.ipv4.conf.lo.arp_announce",  value: "0" }
    - { key: "net.ipv4.conf.all.arp_ignore" ,  value: "0" }
    - { key: "net.ipv4.conf.all.arp_announce", value: "0" }
  when: inventory_hostname in groups['workers']
  notify: Reload Sysctl


- name: Remove Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: absent
  with_items:
    - { key: "net.ipv4.ip_forward",            value: "0" } # In order for the Keepalived service to forward network packets properly to the real servers, each router node must have IP forwarding turned on in the kernel
    - { key: "net.ipv4.ip_nonlocal_bind",      value: "0" } # Load balancing in HAProxy also requires the ability to bind to an IP address that is nonlocal, meaning that it is not assigned to a device on the local system. This allows a running load balancer instance to bind to a an IP that is not local for failover.
  when: inventory_hostname in groups['lb']
  notify: Reload Sysctl

