---
# https://blog.dbi-services.com/using-ansible-to-bring-up-a-three-node-patroni-cluster-in-minutes/
# Nneed to set this so that haproxy can not be started

#- name: Set SELinux Context for HAProxy
#  become: true
#  shell: setsebool -P haproxy_connect_any=0
#  ignore_errors: yes
#  when: inventory_hostname in groups['lb']


- name: Disable the HAProxy Systemd Service
  become: true
  systemd:
    name: haproxy
    enabled: no
    state: stopped
  ignore_errors: yes
  when: inventory_hostname in groups['lb']


- name: Force Systemd to Re-Read Configs
  become: true
  systemd:
    daemon_reload: yes
  when: inventory_hostname in groups['lb']


- name: Uninstall All RPM Packages for HAProxy
  become: true
  yum: name={{ item }} state=absent
  with_items:
   - haproxy
  when: inventory_hostname in groups['lb']


- name: Delete haproxy.cfg
  become: true
  file:
    path: /etc/haproxy
    state: absent
  when: inventory_hostname in groups['lb']


- name: Remove Virtual IP for Direct Service Returns
  import_tasks: remove-dsr-vip.yml
  when: _haproxy.minio.api.lb_mode == "gateway" and inventory_hostname in groups['workers']

