---
- hosts: localhost

  tasks:
    - name: "{{ power_title }} Virtual Machines Without the Answer Param"
      vmware_guest_powerstate:
        hostname: "{{ vmware.esxi_hostname }}"
        username: "{{ vmware.esxi_username }}"
        password: "{{ vmware.esxi_password }}"
        validate_certs: false
        name: "{{ item }}"
        state: "{{ power_state }}"
      loop: "{{ _minio.vms.ubt }}"

