- hosts: localhost

  tasks:
    - name: "{{ power_title }} Virtual Machines Without the Answer Param"
      vmware_guest_powerstate:
        hostname: "{{ _vmware.esxi_hostname }}"
        username: "{{ _vmware.esxi_username }}"
        password: "{{ _vmware.esxi_password }}"
        validate_certs: false
        name: "{{ item }}"
        state: "{{ power_state }}"
      loop: "{{ _minio.vms.rk9 }}"

      #  - "rk9-freeipa"
      #  - "rk9-node01"
      #  - "rk9-node02"
      #  - "rk9-node03"
      #  - "rk9-node04"
      #  - "rk9-node05"
      #  - "rk9-node06"
      #  - "harbor"
      #  - "VMware vCenter Server"

# https://ugurakgul.medium.com/provisioning-a-linux-vm-with-ansible-in-vmware-18cf45a53cb3


