- hosts: localhost
  tasks:
    - name: Download AIStor Software Binaries and Save the into Ansible Files Directory
      become: true
      vars:
        aistor_download_version: "{{ _aistor.major_version }}.{{ _aistor.minor_version }}.{{ _aistor.patch_version }}"
        aistor_rpm_package: "minio.rpm"
        aistor_deb_package: "minio.deb"
        local_dir: "/home/jomoon/AIStor"
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      with_items:
        - { url: "{{ _aistor.download_url }}/{{ aistor_rpm_package }}", dest: "{{ local_dir }}/roles/mnmd/files/{{ aistor_rpm_package }}" }
        - { url: "{{ _aistor.download_url }}/{{ aistor_deb_package }}", dest: "{{ local_dir }}/roles/mnmd/files/{{ aistor_deb_package }}" }
      tags: download

