---
_haproxy:
  cluster_name: minioclu01
  minio_user: minio
  minio_group: minio
  minio_wrapping_port: 5432
  balance_algorithm: roundrobin
  global_max_connections: 4096
  defaults_max_connections: 2000
  user: haproxy
  group: haproxy
  stats_port: 8182
  stats_user: haadmin
  stats_pass: changeme
  minio:
    api:
      frontend_port: 9000
      backend_port: 9000
      balance: leastconn
    console:
      frontend_port: 9001
      backend_port: 9001
      balance: leastconn


# Variables for Role Keepalived
_keepalived:
  auth_pass: "changeme"
  router_id: "52"
  shared_iface: "{{ netdev1 }}"
  shared_ips:
    - { fe: "minio-console" , ipaddr: "192.168.1.179/24" }
    - { fe: "minio-service" , ipaddr: "192.168.1.180/24" }
  check_process: "haproxy"
  priority: "100"
  backup_priority: "50"
  check_script_name: "check_script"
  unicast_mode: False
  unicast_source: "10.0.0.1"
  unicast_peers:
    - "10.0.0.2"
  email: False                         # Setting an email address will install, start and enable postfix
  notification_script: False           # Execute a custom script when state changes - NOT compatible with email notification
  notification_command_backup: False   # Execute a command when state changes to backup
  notification_command_master: False   # Execute a command when state changes to master
  notification_command_fault:  False   # Execute a command when state changes to fault

