---
- name: Umount Data Directory
  mount:
    path: "{{ item.dir }}"
    state: absent
  loop: "{{ _minio.volumes }}"


#- name: Delete MinIO Config and Binary Files
#  file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - "/usr/lib/systemd/system/{{ _minio.service }}-check.timer"
#    - "/usr/lib/systemd/system/{{ _minio.service }}-check.service"
#    - "/etc/default/{{ _minio.service }}"
#    - "/etc/systemd/system/{{ _minio.service }}.service"
#    - "{{ _mc.bin }}"
#    - "{{ _mcli.bin }}"
#    - "{{ _mc.config }}"
#    - "{{ _mcli.config }}"
#    - "{{ _minio.config }}"
#    - "{{ _minio.bin }}"
#    - "{{ _minio.base_path }}/certs"
#    - "{{ _minio.base_path }}/.minio"


- name: Delete MinIO Config and Binary Files
  file:
    path: "{{ item.dir }}"
    state: absent
  with_items: "{{ _minio.volumes }}"


- import_tasks: ext/cleanup-devices.yml

