---
- name: Check Number of Drives in Cluster
  assert:
    that:
      - _minio.volumes|count >= 4
      - _minio.volumes|count <= 16
    msg: Minio cluster work with minimum 4 and maximum 16 drives
  when:
    - _minio.volumes|count > 1


- name: Install MinIO Package
  import_tasks: install-minio-pkgs.yml
  when: _minio.bin_type == "rpm"


- name: Install MinIO Binary
  import_tasks: install-minio-bin.yml
  when: _minio.bin_type == "bin"


- name: Install MinIO Docker
  import_tasks: install-minio-docker.yml
  when: _minio.bin_type == "docker"

