---
- name: Stopping NGINX
  service:
    name: nginx
    state: stopped
  register: stop_nginx
  ignore_errors: true


- name: Uninstall NGINX Package
  yum: name={{ item }} state=absent
  with_items:
    - "{{ nginx_package }}"
    - "nginx-core"


- name: Remove NGINX Repository ( and clean up left-over metadata )
  yum_repository:
    name: epel
    file: nginx_repo
    state: absent


- name: Delete NGINX Config Files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/nginx.conf"


- name: Stopping MinIO
  systemd:
    name: minio
    state: stopped
  ignore_errors: true


- name: Uninstall MinIO Package
  yum: name={{ item }} state=absent
  with_items:
    - minio
    - mcli


- name: Force Systemd to Reload Configs
  systemd:
    daemon_reload: yes

