---
_mc:
  release_date: 2025-05-21T01-59-54Z
  patch_version: 1
  download_url: https://dl.minio.io/client/mc/release/linux-amd64
  download_archive_url: https://dl.minio.io/client/mc/release/linux-amd64/archive
  download: false
  checksum:
  bin: /usr/local/bin/mc
  bin_dir: /usr/local/bin
  config: "/home/minio/.mc/config.json"
  config_opts:
    hosts:
      minio:
        url: https://{{ ansible_host | default('localhost') }}:{{ _minio.api_port }}
        accessKey: "{{ _minio.access_key }}"
        secretKey: "{{ _minio.secret_key }}"
        api: S3v4


_mcli:
  release_date: 20250521015954.0.0
  patch_version: 1
  download_url: https://dl.minio.io/client/mc/release/linux-amd64
  download_archive_url: https://dl.minio.io/client/mc/release/linux-amd64/archive
  download: false
  checksum:
  bin: /usr/local/bin/mcli
  config: "/home/minio/.mc/config.json"
  config_opts:
    hosts:
      minio:
        url: https://{{ ansible_host | default('localhost') }}:{{ _minio.api_port }}
        accessKey: "{{ _minio.access_key }}"
        secretKey: "{{ _minio.secret_key }}"
        api: S3v4


_warp:
  download: false
  download_url: https://github.com/minio/warp/releases/download
  major_version: 1
  minor_version: 1
  patch_version: 6
  bin: /usr/bin/warp

