---
- name: Add Docker-CE Repository
  yum_repository:
    name: docker-ce
    description: Add docker repsotiry
    baseurl: "https://download.docker.com/linux/centos/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/stable/"
    gpgcheck: "no"
  register: add_docker_ce_repo
- debug: msg={{ add_docker_ce_repo }}


- name: Install Docker-CE Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker-ce"
  register: install_docker_ce
- debug: msg={{ install_docker_ce }}


- name: Enable and Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
  register: start_docker
  until: start_docker is succeeded
  retries: 10
- debug: msg={{ start_docker }}

