---
- name: Apply Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "net.ipv4.conf.lo.arp_ignore" ,   value: "1" }
    - { key: "net.ipv4.conf.lo.arp_announce",  value: "2" }
    - { key: "net.ipv4.conf.all.arp_ignore" ,  value: "1" }
    - { key: "net.ipv4.conf.all.arp_announce", value: "2" }
  when: inventory_hostname in groups['workers']
  notify: Reload Sysctl


- name: Apply Kernel Parameters for Direct Routing Virutal IP Address
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "net.ipv4.ip_forward",            value: "1" } # In order for the Keepalived service to forward network packets properly to the real servers, each router node must have IP forwarding turned on in the kernel
    - { key: "net.ipv4.ip_nonlocal_bind",      value: "1" } # Load balancing in HAProxy also requires the ability to bind to an IP address that is nonlocal, meaning that it is not assigned to a device on the local system. This allows a running load balancer instance to bind to a an IP that is not local for failover.
  when: inventory_hostname in groups['lb']
  notify: Reload Sysctl


- name: Configure Virutal IP Address for Direct Routing
  shell: |
    ifconfig lo:{{ item.netidx }} {{ item.ipaddr.split('/')[:-1] | join('/') }} netmask {{ item.netmask }}
  register: config_direct_routing_vip
  with_items: "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']


- name: Add Virtual Services
  shell: |
    ipvsadm -A -t {{ item.ipaddr.split('/')[:-1] | join('/') }}:{{ item.src_port }} -s {{ item.lb_mode }}
  register: add_virtual_services
  with_items:
    - "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['lb']
- debug: msg={{ add_virtual_services }}
  when: inventory_hostname in groups['lb']


- name: Add Active Real Servers ( IPIP/TUN0 or Direct )
  shell: |
    ipvsadm -a -t {{ item.ipaddr.split('/')[:-1] | join('/') }}:{{ item.src_port }} \
    -r {{ hostvars[inventory_hostname][_netdev].ipv4.address }}:{{ item.dest_port }} -g
  delegate_to: "{{ hostvars[groups['lb'][0]]['ansible_hostname'] }}"
  delegate_facts: True
  register: add_active_real_servers
  with_items:
    - "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']
- debug: msg={{ add_active_real_servers }}
  when: inventory_hostname in groups['workers']


- name: Backup Active Real Servers ( IPIP/TUN0 or Direct )
  shell: |
    ipvsadm -a -t {{ item.ipaddr.split('/')[:-1] | join('/') }}:{{ item.src_port }} \
    -r {{ hostvars[inventory_hostname][_netdev].ipv4.address }}:{{ item.dest_port }} -g
  delegate_to: "{{ hostvars[groups['lb'][1]]['ansible_hostname'] }}"
  delegate_facts: True
  register: add_backup_real_servers
  with_items:
    - "{{ _keepalived.shared_ips }}"
  when: inventory_hostname in groups['workers']
- debug: msg={{ add_backup_real_servers }}
  when: inventory_hostname in groups['workers']


- name: List Virtual Services
  shell: |
    ipvsadm -Ln
  register: list_virtual_services
  when: inventory_hostname in groups['lb']
- debug: msg={{ list_virtual_services }}
  when: inventory_hostname in groups['lb']



# https://www.lisenet.com/2015/setting-up-a-load-balancing-haproxy-cluster-with-keepalived
# https://docs.oracle.com/en/operating-systems/oracle-linux/6/admin/section_wkd_ys2_4r.html
# https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/load_balancer_administration/s1-lvs-direct-VSA#s2-lvs-direct-arptables-VSA

