---
- name: Get NVME Devices With a Line
  shell: |
    nvme list | sed 1,2d | awk '{print $1}' | cut -d "/" -f 3 | tr '\n' ' ' | sed -e 's/ $//'
  register: nvme_devices_line
- debug: msg={{ nvme_devices_line.stdout_lines }}
  when: print_debug == true


- name: Set Fact for NVME Devices with a Line
  set_fact:
    nvme_devices: "{{ nvme_devices_line.stdout }}"
- debug: msg={{ nvme_devices }}
  when: print_debug == true


- name: Get NVME Devices Count
  shell: |
    nvme list | sed 1,2d | awk '{print $1}' | wc -l
  register: nvme_device_count0
- debug: msg={{ nvme_device_count0.stdout_lines }}
  when: print_debug == true


- name: Set NVME Device Count
  set_fact:
    nvme_device_count: "{{ nvme_device_count0.stdout }}"
- debug: msg={{ nvme_device_count }}
  when: print_debug == true


#- name: Set NVME Device Count - Tested to check selecting min values
#  set_fact:
#    nvme_device_count: "2"
#  when: inventory_hostname in groups['control']
#- debug: msg={{ nvme_device_count }}
#  when: print_debug == true and inventory_hostname in groups['control']


- name: Collect all custom facts from hosts
  set_fact:
    nvme_device_count_list: "{{ groups['workers'] | map('extract', hostvars, 'nvme_device_count') | list }}"


- name: Get the Minimum value
  set_fact:
    nvme_count_min_value: "{{ nvme_device_count_list | min }}"


- name: Print Result
  debug: msg="Minimum Value of 'my_value' across All Hosts - {{ nvme_count_min_value }}"


- name: Get NVME Devices List
  shell: |
    nvme list | sed 1,2d | awk '{print $1}' | paste -sd "," -
  register: nvme_device_list0
- debug: msg={{ nvme_device_list0.stdout_lines }}
  when: print_debug == true


- name: Set NVME Device List
  set_fact:
    nvme_device_list: "{{ nvme_device_list0.stdout }}"
- debug: msg={{ nvme_device_list }}
  when: print_debug == true


- name: Get NVME Devices Array
  shell: |
    nvme list | sed 1,2d | awk '{print $1}'
  register: nvme_device_array0
- debug: msg={{ nvme_device_array0.stdout_lines }}
  when: print_debug == true


- name: Set Number of NVME Devices
  set_fact:
    nvme_device_count: "{{ nvme_device_array0.stdout_lines|length }}"
- debug: msg={{ nvme_device_count }}
  when: print_debug == true


- name: Set NVME Device Arrary
  set_fact:
    nvme_device_array: "{{ nvme_device_array0.stdout_lines }}"
- debug: msg={{ nvme_device_array }}
  when: print_debug == true

