---
- name: Check if MinIO Client Binary Already Exists
  stat: path={{ minio_client_bin }}
  register: mc_bin_exists


- name: Copy MinIO Client Binary from Local Directory
  copy: src=mc-{{ minio.release_date }}.tar.gz dest=/tmp/mc-{{ minio.release_date }}.tar.gz mode=0644 owner=root group=root
  register: mc_local_copy
  when: mc_bin_exists.stat.exists == false and minio_download == false


- name: Unarchive MinIO Client
  unarchive:
    src: "/tmp/mc-{{ minio.release_date }}.tar.gz"
    dest: "/usr/local/bin"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes
    # extra_opts:
    #- --transform
    #- s/^xxx/yyy/
  register: mc_unarchive
  when: mc_bin_exists.stat.exists == false and minio_download == false


- name: Download MinIo Client
  get_url:
    url: "{{ minio_client_url }}"
    dest: "{{ minio_client_bin }}"
    checksum: "{{ minio_client_checksum | d(omit) }}"
    mode: 0755
    timeout: 20
  when: ( minio_client_url.endswith('mc') or minio_client_url.endswith('Z') ) and ( mc_bin_exists.stat.exists == false and minio_download == true )


- name: Install Unzip
  yum: name=unzip
  when: minio_client_url.endswith('zip') and ( mc_bin_exists.stat.exists == false and minio_download == false )


- name: Unarchive MinIO Client
  unarchive:
    src: "{{ minio_client_url }}"
    dest: "{{ minio_client_bin | dirname }}"
    remote_src: "{{ minio_client_url.startswith('http') }}"
    mode: 0755
  when: minio_client_url.endswith('zip') and ( mc_bin_exists.stat.exists == false and minio_download == false )

