---
- name: Check OS ( MinIO )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Configure Firewalld for MinIO
  import_tasks: firewalld.yml
  tags: install
  when: open_firewall


- name: Enable SSL
  import_tasks: enable-ssl.yml
  tags: install
  when: enable_ssl


- name: Install MinIO
  import_tasks: minio.yml
  tags: install
  when: install_minio


- name: Install NGINX
  import_tasks: nginx.yml
  tags: install
  when: use_nginx


- name: Uninstall MinIO
  import_tasks: uninstall.yml
  tags: uninstall


- name: Upgrade MinIO
  import_tasks: upgrade.yml
  tags: upgrade

