---
- name: Copy Defaults Options Template
  template:
    src: minio_opt.j2
    dest: /etc/default/{{ _minio.service }}


- name: Copy Systemd Service Template
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/{{ _minio.service }}.service


- name: Start MinIO
  systemd: name={{ _minio.service }} state=started enabled=yes daemon_reload=yes


- name: Force to Restart MinIO Server
  meta: flush_handlers

