---
- name: Umount Data Directory
  mount:
    path: "{{ item.dir }}"
    state: absent
  loop: "{{ _minio.volumes }}"


- name: Delete MinIO Config and Binary Files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/lib/systemd/system/{{ _minio.service }}-check.timer"
    - "/usr/lib/systemd/system/{{ _minio.service }}-check.service"
    - "/etc/default/{{ _minio.service }}"
    - "/etc/systemd/system/{{ _minio.service }}.service"
    - "{{ _minio.config }}"
    - "{{ _minio.bin }}"
    - "{{ minio_bin }}"
    - "/root/certs"
    - "/root/.minio"
    - "/etc/nginx/nginx.conf"
    - "/etc/nginx/conf.d/minio.conf"
    - "/home/minio/certs"
    - "/home/minio/.minio"
    - "/tmp/{{ minio_pkg_name }}"


- name: Delete MinIO Config and Binary Files
  file:
    path: "{{ item.dir }}"
    state: absent
  with_items: "{{ _minio.volumes }}"


- import_tasks: ext/cleanup-devices.yml

