---
- name: Create SSL Directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ _minio.user }}"
    group: "{{ _minio.group }}"
  register: create_ssl_dir
  with_items:
    - "{{ _ssl.ssl_dir }}"
    - "{{ _minio.base_path }}/.minio/certs"
    - "{{ _minio.base_path }}/.minio/certs/{{ inventory_hostname }}.{{ _minio.domain }}"
    - "{{ _minio.base_path }}/.minio/certs/minio-vm-lb.{{ _minio.domain }}"
    - "{{ _minio.base_path }}/.minio/certs/CAs"
    - "/root/.minio/certs"
    - "/root/.minio/certs/{{ inventory_hostname }}.{{ _minio.domain }}"
    - "/root/.minio/certs/minio-vm-lb.{{ _minio.domain }}"
    - "/root/.minio/certs/CAs"
  when: _minio.ssl is defined and _minio.ssl == true


- name: Generate TLS Keys
  shell: |
    certgen -host "localhost,{{ ansible_fqdn }}"
  register: gen_tls_keys
  args:
    executable: /bin/bash
    chdir: "{{ _ssl.ssl_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: _minio.ssl is defined and _minio.ssl == true


- name: Change Permission of SSL Key Files
  file:
    path: "{{ _ssl.ssl_dir }}/{{ item }}"
    state: file
    owner: "{{ _minio.user }}"
    group: "{{ _minio.group }}"
    mode: "0600"
  with_items:
    - "private.key"
    - "public.crt"
  when: _minio.ssl is defined and _minio.ssl == true


- name: Copy File with Owner and Permissions
  copy:
    src: "{{ item.org }}"
    dest: "{{ item.dest }}"
    owner: "{{ _minio.user }}"
    group: "{{ _minio.group }}"
    mode: 0644
    remote_src: yes
  with_items:
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "{{ _minio.base_path }}/.minio/certs/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "{{ _minio.base_path }}/.minio/certs/private.key" }
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "{{ _minio.base_path }}/.minio/certs/{{ inventory_hostname }}.{{ _minio.domain }}/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "{{ _minio.base_path }}/.minio/certs/{{ inventory_hostname }}.{{ _minio.domain }}/private.key" }
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "{{ _minio.base_path }}/.minio/certs/minio-vm-lb.{{ _minio.domain }}/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "{{ _minio.base_path }}/.minio/certs/minio-vm-lb.{{ _minio.domain }}/private.key" }
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "{{ _minio.base_path }}/.minio/certs/CAs/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "{{ _minio.base_path }}/.minio/certs/CAs/private.key" }
  when: ( _minio.ssl is defined and _minio.ssl == true ) and (  _minio.bin_type is defined and _minio.bin_type != "docker" )


- name: Copy File with Owner and Permissions
  copy:
    src: "{{ item.org }}"
    dest: "{{ item.dest }}"
    owner: "{{ _minio.user }}"
    group: "{{ _minio.group }}"
    mode: 0644
    remote_src: yes
  with_items:
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "/root/.minio/certs/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "/root/.minio/certs/private.key" }
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "/root/.minio/certs/{{ inventory_hostname }}.{{ _minio.domain }}/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "/root/.minio/certs/{{ inventory_hostname }}.{{ _minio.domain }}/private.key" }
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "/root/.minio/certs/minio-vm-lb.{{ _minio.domain }}/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "/root/.minio/certs/minio-vm-lb.{{ _minio.domain }}/private.key" }
    - { org: "{{ _ssl.ssl_dir }}/public.crt",  dest: "/root/.minio/certs/CAs/public.crt" }
    - { org: "{{ _ssl.ssl_dir }}/private.key", dest: "/root/.minio/certs/CAs/private.key" }
  when: ( _minio.ssl is defined and _minio.ssl == true ) and (  _minio.bin_type is defined and _minio.bin_type == "docker" )

