---
- name: Check if MinIO Binary Already Exists
  stat: path={{ _minio.bin }}
  register: minio_bin_exists
- debug: msg={{ minio_bin_exists }}


- name: Copy MinIO Package from Local Directory
  copy: src={{ minio_pkg_name }} dest=/tmp/{{ minio_pkg_name }} mode=0644 owner=root group=root
  register: minio_local_copy
  when: minio_bin_exists.stat.exists == false and _minio.download == false


- name: Download MinIO Server Package
  get_url:
    url: "{{ _minio.download_url }}/{{ minio_pkg_name }}"
    dest: "/tmp/{{ minio_pkg_name }}"
    mode: 0644
    checksum: "{{ _minio.server_checksum | d(omit) }}"
  when: ( _minio.download_url.endswith('minio') or ( _minio.download_url + '/' + minio_pkg_name ).endswith('rpm') ) and ( minio_bin_exists.stat.exists == false and _minio.download == true )


- name: Install MinIO Package from Local Directory
  package:
    name: /tmp/{{ minio_pkg_name }}
    state: present
    disable_gpg_check: yes
  when: minio_bin_exists.stat.exists == false

