---
- name: Add NGINX Repo
  yum_repository:
    name: nginx
    description: NGINX YUM Repository
    baseurl: >
      http://nginx.org/packages/{{(ansible_distribution == "RedHat") |
      ternary('rhel', 'centos')}}/{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
  when: nginx_package == 'nginx'


- name: Installing NGINX
  yum: name={{ nginx_package }} validate_certs=no


- name: Copy NGINX Config
  template:
    src: "{{ item.fn }}"
    dest: "{{ item.dest }}"
  register: copy_nginx_config
  with_items:
    - { fn: "nginx.conf.j2", dest: "/etc/nginx/nginx.conf" }
    - { fn: "minio.conf.j2", dest: "/etc/nginx/conf.d/minio.conf" }
  notify: Restart NGINX
  # - { fn: "default.conf.j2", dest: "/etc/nginx/conf.d/default.conf" }


- name: Show NGINX Address
  debug: msg="Minio Cluster Address http://{{ inventory_hostname }}.{{ _minio.domain }}/minio"


- name: Starting NGINX
  service:
    name: nginx
    state: started

