---
- name: Check OS ( Single MinIO - SNMD )
  fail: msg="Not a Red Hat based system!"
  when: ansible_facts['distribution'] not in ['RedHat', 'CentOS', 'Rocky', 'Debian', 'Ubuntu']


- name: Set Facts for Network and Packages Informations
  import_tasks: set-minio-facts.yml
  tags: install, uninstall, create, delete, setup, remove, upload, download, enable, disable, mount, umount


- name: Configure Firewalld for MinIO
  import_tasks: security/disable-firewall.yml
  tags: disable, install
  when: (( firewall is defined and firewall == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Enable Docker Repository
  import_tasks: docker/enable-docker-repo.yml
  tags: enable, install
  when: (( docker is defined and docker == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Create Data Devices
  import_tasks: create-data-device.yml
  tags: create, mount, install
  when: (( dev is defined and dev == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Enable SSL
  import_tasks: enable-minio-ssl.yml
  tags: enable, install
  when: (( ssl is defined and ssl == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Install MinIO
  import_tasks: install-minio.yml
  tags: setup, install
  when: (( minio is defined and minio == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Configure MinIO
  import_tasks: config-minio.yml
  tags: config, install
  when: (( minio is defined and minio == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Install NGINX
  import_tasks: install-nginx.yml
  tags: setup, install
  when: (( nginx is defined and nginx == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Uninstall NGINX
  import_tasks: uninstall-nginx.yml
  tags: remove, uninstall
  when: (( nginx is defined and nginx == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Uninstall MinIO
  import_tasks: uninstall-minio.yml
  tags: remove, uninstall
  when: (( minio is defined and minio == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Delete Data Devices
  import_tasks: delete-data-device.yml
  tags: delete, umount, uninstall
  when: (( dev is defined and dev == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Disable Docker Repository
  import_tasks: docker/disable-docker-repo.yml
  tags: disable, uninstall
  when: (( docker is defined and docker == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']


- name: Upgrade MinIO
  import_tasks: upgrade-minio.yml
  tags: upgrade
  when: (( minio is defined and minio == true ) or ( snmd_all is defined and snmd_all == true )) and inventory_hostname in groups['workers']

