---
- name: Stopping MinIO Docker
  systemd:
    name: minio-docker
    state: stopped


#- name: Stop and Remove Docker Imgages
#  shell: |
#    docker stop minio && docker rm minio
#  register: stop_docker_image
#  ignore_errors: true


- name: Force Remove Docker Imgages at Once
  shell: |
    for i in `docker images | sed 1d | awk '{print $3}'`; do docker image rm $i --force ; done
  register: force_remove_docker_images
  ignore_errors: true


- name: Force Systemd to Reload Configs
  systemd:
    daemon_reload: yes

