---
- name: Stopping NGINX
  service:
    name: nginx
    state: stopped
  register: stop_nginx
  ignore_errors: true


- name: Uninstall NGINX Package
  yum: name={{ item }} state=absent
  with_items:
    - "nginx-core"
    - "{{ _nginx.package }}"


- name: Remove NGINX Repository ( And Clean Up Left-Over Metadata )
  yum_repository:
    name: epel
    file: nginx_repo
    state: absent


- name: Delete NGINX Config Files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/conf.d/minio.conf"
    - "/etc/nginx/nginx.conf"
    - "/etc/nginx/nginx.conf.rpmsave"
    - "/etc/nginx/conf.d"

