---
- name: Check if Warp Binary Already Exists
  stat: path={{ _warp.bin }}
  register: check_warp_bin


- name: Copy Warp Package from Local Directory
  copy: src={{ warp_pkg_name }} dest=/tmp/{{ warp_pkg_name }} mode=0644 owner=root group=root
  register: mc_local_copy
  when: check_warp_bin.stat.exists == false and _warp.download == false


- name: Download Warp Package
  get_url:
    url: "{{ _warp.download_url }}/v{{ warp_version }}/{{ warp_pkg_name }}"
    dest: "/tmp/{{ warp_pkg_name }}"
    mode: 0644
  when: ( ( _warp.download_url + '/v' + warp_version + '/' + warp_pkg_name ).endswith('warp') or ( _warp.download_url + '/v' + warp_version + '/' + warp_pkg_name ).endswith('rpm') ) and ( check_warp_bin.stat.exists == false and _warp.download == true )


- name: Install Warp Package from Local Directory
  package:
    name: /tmp/{{ warp_pkg_name }}
    state: present
    disable_gpg_check: yes
  when: check_warp_bin.stat.exists == false


- name: Run Warp Benchmark from Workers
  shell: |
    {{ _warp.bin }} mixed {{ minio_warp_option }} --host {{ _ipaddr }}:{{ _minio.api_port }} --access-key {{ _minio.access_key }} \
    --secret-key {{ _minio.secret_key }} --duration {{ _warp.duration }} --objects {{ _warp.objects }} --concurrent {{ _warp.concurrent }}
  register: run_warp_workers
  when: inventory_hostname in groups['workers']
- debug: msg="{{ run_warp_workers }}"
  when: inventory_hostname in groups['workers']


- name: Run Warp Benchmark from Non Workers
  shell: |
    {{ _warp.bin }} mixed {{ nginx_warp_option }} --host {{ _nginx.minio.api.hostname }}.{{ _nginx.minio.api.domain }} --access-key {{ _minio.access_key }} \
    --secret-key {{ _minio.secret_key }} --duration {{ _warp.duration }} --objects {{ _warp.objects }} --concurrent {{ _warp.concurrent }}
  register: run_warp_non_workers
  when: inventory_hostname not in groups['workers']
- debug: msg="{{ run_warp_non_workers }}"
  when: inventory_hostname not in groups['workers']

