---
- name: Install Upgrade Pip
  shell: |
    export PATH=$PATH:/usr/local/bin && pip3 install --upgrade pip
  register: upgrade_pip
- debug: msg={{ upgrade_pip }}
  when: print_debug == true


- name: Upgrade SetupTools
  shell: |
    export PATH=$PATH:/usr/local/bin && pip3 install --upgrade --ignore-installed pip setuptools
  register: upgrade_setuptools
- debug: msg={{ upgrade_setuptools }}
  when: print_debug == true


- name: Install SetupTools Rust
  shell: |
    export PATH=$PATH:/usr/local/bin && pip3 install setuptools_rust
  register: setuptools_rust
- debug: msg={{ setuptools_rust }}
  when: print_debug == true


- name: Install Docker-Compose
  shell: |
    export PATH=$PATH:/usr/local/bin && pip3 install docker-compose
  register: install_docker_compose
- debug: msg={{ install_docker_compose }}
  when: print_debug == true


- name: Enable and Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon-reload: yes
  register: enable_docker
  until: enable_docker is succeeded
  retries: 30
  delay: 10
  failed_when: enable_docker is failure
- debug: msg={{ enable_docker }}
  when: print_debug == true


- name: Verify that Docker is Installed Correctly by Running the Hello-World Image
  shell: |
    docker run hello-world
  ignore_errors: yes
  register: run_docker_hello
- debug: msg={{ run_docker_hello }}
  when: print_debug == true

