---
- name: Add Docker Repository in All Nodes
  yum_repository:
    name: docker-ce
    description: Add docker repsotiry
    baseurl: "https://download.docker.com/linux/centos/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/stable/"
    gpgcheck: "no"
  when: ansible_distribution_major_version|int >= 9


- name: Install Docker-CE Packages of the Latest Version in All Nodes
  package:
    name: "{{ rh_docker_pkgs }}"
    state: present
  when: ansible_distribution_major_version|int >= 9


# https://github.com/dogukancagatay/docker-cassandra-web

